### ISSUE TITLE
Module name change

### ISSUE THREAD

**Issue by davinhanlon** [PureStorage-OpenConnect/purestorage-puppet#1]
Hi,

I work at Puppet as the modules product owner. I noticed that this module is named simply 'Puppet'. From looking at the code, it's defined as 'Pure', so the module should be named 'Pure' and not 'Puppet'.

It is not not a good idea to use the name 'Puppet' for a module, as it doesn't describe the application  the module manages. It would be best for the name of this module to reflect the name of the application which is manages, i.e. 'Pure'.

Thanks,
Davin

**Comment by sdodsley** [comment]
@davinhanlon thanks for raising this. We are going to refactor this code soon, so will apply the appropriate changes then.

**Comment by davinhanlon** [comment]
Excellent, thanks for the prompt follow up @sdodsley .

**Comment by fatmcgav** [comment]
@sdodsley What's the latest on any refactor efforts? 

As I've got an internal requirement to manage our Pure arrays via Puppet, and this module is missing some functionality around snapshots etc... So before I dive in and add support would be good to know if the code base is still current...

**Comment by sdodsley** [comment]
Eventually got around to publishing the new version of this module. Now called purestorage-purefa
